### ISSUE TITLE
Implement map system

### ISSUE THREAD

**Issue by louis030195** [MephisTools/PathOfBot#6]
Options:
- Disasemble Game.exe and find the map generation algorithm (hard)
- Injector (medium)
- Kind of random guessing of the layout (for maps that we can guess)(easy) (or just make the bot rush the warps when getting D2GS_ASSIGNLVLWARP)

then pathfinding

**Comment by rom1504** [comment]
"random guessing" through path finding is done.
we can create more issues to track using the game files or other ideas if needed
